window.GB_SUPABASE_CONFIG = {
  url: https://cuxcgfdstqxhxvcyyqtp.supabase.co/rest/v1/,
  anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1eGNnZmRzdHF4aHh2Y3l5cXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NDI1MzksImV4cCI6MjA5NTAxODUzOX0.ihBzgVOglFzcCIkp10U72tGKoBdyKs6FJWmpKdg5o-o
};